#!/bin/bash
#Post Installion

check_for_internet()
{
nc -z 8.8.8.8 53  >/dev/null 2>&1
online=$?
if [ $online -eq 0 ]; then
    return 0
else
    return 1
fi
}

loadkeys()
{
    loadkeys lv &
}

update_system_clock()
{
    timedatectl set-ntp true
}

edit_mirrorlist()
{
    vim /etc/pacman.d/mirrorlist && pacman -Syyy
}

edit_partions()
{
    lsblk
    echo -e " What partion you want to edit (like dev/sxx): "
    read partion_to_edit
    fdisk $partion_to_edit
}

makefs_partions()
{
    lsblk
    echo -e "Enter partion name for boot partion:"
    read boot_partion_to_make
    echo -e "Enter partion name for root partion:"
    read root_partion_to_make
    
    mkfs.fat -F32 $boot_partion_to_make
    mkfs.ext4 $root_partion_to_make
}

mount_made_partions()
{
    mount $root_partion_to_make /mnt
    mkdir /mnt/boot
    mount $boot_partion_to_make /mnt/boot
}

pacstrap_packages()
{
    local base_packages="base base-devel linux linux-firmware vim gnu-netcat"
    pacstrap /mnt $base_packages
}

genfstab_file()
{
    genfstab -U /mnt >> /mnt/etc/fstab
}

change_archroot()
{
    arch-chroot /mnt ./Arch-Setup
}
make_setup_executable()
{
chmod +x /mnt/Arch-Setup
}

install()
{
    check_for_internet
    if [[ $? == 0 ]]; then
        loadkeys &&\
            update_system_clock &&\
            edit_mirrorlist &&\
            edit_partions &&\
            makefs_partions &&\
            mount_made_partions &&\
            pacstrap_packages &&\
            create_copy_setup &&\
            make_setup_executable &&\
            genfstab_file &&\
            change_archroot\
            || echo "Error"
    else
        echo "No internet, check for internet connection"
    fi
}

install
